{% set name = "types-pysftp" %}
{% set version = "0.2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pysftp-{{ version }}.tar.gz
  sha256: c0cb602db0c6a3fd29cde36cda4d4c9a600c1895138ef7e6aa173bb075d66891

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-paramiko

test:
  commands:
    - test -f $SP_DIR/pysftp-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pysftp
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
