{% set name = "types-pysftp" %}
{% set version = "0.2.17.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pysftp-{{ version }}.tar.gz
  sha256: 9dbabc7bf0780d7cbb2e681723e6053246e8f04607c97274f8a1778177ab42ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-paramiko

test:
  commands:
    - test -f $SP_DIR/pysftp-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pysftp
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
